package vet.center.api.domain.anamnese;

import java.time.LocalDateTime;

public record DadosAnamnese(
        DadosAnamneseProprietario proprietario,
        DadosAnamneseAnimal animal,
        DadosAnamneseVeterinario veterinario,
        String anamnese,
        String tr,
        String estado,
        String mucosas,
        String linfonodos,
        String tpc,
        String turgorCutaneo,
        String desidratacao,
        Boolean ectoparasitas,
        Boolean mioclonias,
        String prurido,
        Boolean vomito,
        Boolean diarreia,
        String inapatencia,
        String secrecoesPatologicas,
        String calculoDentario,
        String auscultacaoPulmonar,
        String auscultacaoCardiaca,
        String reflexoToce,
        String emagrecimento,
        String alteracaoComportamental,
        String observacoes,
        String extoscopia,
        String cavidadeAbdominal,
        String cabecaPescoco,
        String sistemaNervoso,
        String sistemaLocomotor,
        Boolean cansaco,
        Boolean tosse,
        String pulso,
        String fc,
        String fr,
        String observacoes2,
        String examesComplementares,
        String diagnostico,
        String prognostico,
        String tratamento,
        String retorno,
        Long veterinarioId,
        Long animalId,
        Long proprietarioId,
        LocalDateTime data) {
}
